#!/usr/bin/env python3
"""Dump PB sync_config + sync_global to a YAML snapshot.

Output: notion_sync/registry.snapshot.yaml (committed to git for disaster
recovery). Manual — runs only when invoked, not on PB writes.
"""
from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from notion_sync.pb_api import PBClient


HEADER = """\
# Auto-generated by scripts/dump_sync_registry.py.
# Source of truth: PB sync_config / sync_global tables.
# Regenerate after every UI change:
#   python scripts/dump_sync_registry.py
# and commit the diff so disaster-recovery git can rebuild PB.
"""


def _yaml_scalar(v) -> str:
    """Encode a single value (str, int, bool, None) as a YAML scalar."""
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    s = str(v)
    if (s == "" or any(c in s for c in ":#\n") or s[:1] in (" ", "-", "?", "@")
        or s.lower() in ("null", "true", "false", "yes", "no")):
        return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'
    return s


def _emit_dict_inline(d: dict) -> str:
    if not d:
        return "{}"
    parts = [f'{k}: {_yaml_scalar(v)}' for k, v in d.items()]
    return "{" + ", ".join(parts) + "}"


def render(sync_global: dict | None, targets: list[dict]) -> str:
    lines = [HEADER.rstrip(), ""]
    lines.append(f'generated_at: "{datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")}"')
    lines.append("sync_global:")
    g = sync_global or {}
    for key in ("timezone", "sync_hour_local", "sync_hour_local_2",
                "paused", "last_run_at"):
        lines.append(f"  {key}: {_yaml_scalar(g.get(key))}")
    lines.append("sync_targets:")
    for t in targets:
        lines.append(f"  - collection: {_yaml_scalar(t.get('collection'))}")
        for key in ("notion_db_id", "enabled", "auto_sync",
                    "title_field", "date_field"):
            lines.append(f"    {key}: {_yaml_scalar(t.get(key))}")
        overrides = t.get("field_map_overrides") or {}
        lines.append(f"    field_map_overrides: {_emit_dict_inline(overrides)}")
        for key in ("last_synced_at", "last_sync_summary"):
            lines.append(f"    {key}: {_yaml_scalar(t.get(key))}")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--path", default="notion_sync/registry.snapshot.yaml")
    ap.add_argument("--stdout", action="store_true")
    args = ap.parse_args()

    try:
        pb = PBClient()
        globals_ = pb.list_records("sync_global", sort="")
        sync_global = globals_[0] if globals_ else None
        targets = pb.list_records("sync_config", sort="collection")
    except Exception as e:
        print(f"error: {e}", file=sys.stderr)
        return 1

    text = render(sync_global, targets)
    if args.stdout:
        sys.stdout.write(text)
    else:
        out = Path(args.path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text, encoding="utf-8")
        print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
